### PR TITLE
Added declaration of ts types

### PR DESCRIPTION
**Pull request by iulianraduat**
Hi @maxfahl,

I want to use your package in a typescript project and VSCodes complains that there is no typedef for it.
I found a workaround to import the types but it will be great if you have it also defined via package.json.

Please review this PR and test if it automatically provides a typedef for typescript.

Many thanks for creating this package. If you approve and merge this PR or your own solution then let me know so I can advertise this package on my LinkedIn account.

Cheers,
Iulian

### CODE REVIEW

**Comment by iulianraduat** [comment]
Hi @maxfahl,

We need to also add the "global.d.ts" in final package and in the types as otherwise  we get:
```
node_modules/matomo-react/src/MatomoTracker.ts:57:12 - error TS2339: Property '_paq' does not exist on type 'Window & typeof globalThis'.

57     window._paq = window._paq || []
```

Thanks,
Iulian

**Comment by maxfahl** [comment]
Thanks. Will take a look tomorrow. If theres nothing weird I'll just push a new version to npm.

**Comment by maxfahl** [comment]
Sorry for the delay, has had my ass full. Will add the global.d.ts tomorrow.

**Comment by maxfahl** [comment]
Sorry, didn't get around to fixing the last part yet. Too much work and kids stuff. If you need the fix, and you don't mind creating a PR for the global.d.ts, I can merge it and push it to npm tonight.

**Comment by maxfahl** [comment]
I actually don't have any problems with the existing global.d.ts, but I improved it a bit anyway. Hopefully it'll work for you. Changes are now live on npm.

**Pull request merged**
